language: node_js

branches:
  only:
    - master

node_js:
  - "10.18"

jobs:
  include:
    - stage: build-and-deploy
      script:
        - npm run build && npm run semantic-release

stages:
  - name: build-and-deploy
    if: branch = master AND type = push

